Repository fivetran/dbt_ad_reporting, pull requests merged in 2022-09, with the labels that each got.

#60 fixing linkedin ads database and schema variable names in readme
  README.md
Labels: bug, documentation

#57 metrics woot woot
  CHANGELOG.md
  README.md
  integration_tests/requirements.txt
  models/ad_reporting_metrics.yml
  models/ad_reporting_models.yml
Labels: enhancement

#61 release/v1.0.1
  CHANGELOG.md
  README.md
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/requirements.txt
  models/ad_reporting_metrics.yml
  models/ad_reporting_models.yml
Labels: documentation
